
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
/// <summary>
/// 物品
/// </summary>
public sealed partial class Award : Luban.BeanBase
{
    public Award(ByteBuf _buf) 
    {
        ItemId = _buf.ReadInt();
        Num = _buf.ReadInt();
        PostInit();
    }

    public static Award DeserializeAward(ByteBuf _buf)
    {
        return new Award(_buf);
    }

    public readonly int ItemId;
    public readonly int Num;
   
    public const int __ID__ = 63670845;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "ItemId:" + ItemId + ","
        + "Num:" + Num + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}

}
