
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public sealed partial class QUEST_CONST : Luban.BeanBase
{
    public QUEST_CONST(ByteBuf _buf) 
    {
        PlanDaily = _buf.ReadInt();
        PlanWeekly = _buf.ReadInt();
        MaxQuestCount = _buf.ReadInt();
        MaxTalkOneDay = _buf.ReadInt();
        PlanHome = _buf.ReadInt();
        PostInit();
    }

    public static QUEST_CONST DeserializeQUEST_CONST(ByteBuf _buf)
    {
        return new QUEST_CONST(_buf);
    }

    /// <summary>
    /// 日常任务方案
    /// </summary>
    public readonly int PlanDaily;
    /// <summary>
    /// 周常任务方案
    /// </summary>
    public readonly int PlanWeekly;
    /// <summary>
    /// 日常周常任务最大刷新数量
    /// </summary>
    public readonly int MaxQuestCount;
    /// <summary>
    /// 每天发言最多的人邮件
    /// </summary>
    public readonly int MaxTalkOneDay;
    /// <summary>
    /// 家园任务方案
    /// </summary>
    public readonly int PlanHome;
   
    public const int __ID__ = -558913146;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "PlanDaily:" + PlanDaily + ","
        + "PlanWeekly:" + PlanWeekly + ","
        + "MaxQuestCount:" + MaxQuestCount + ","
        + "MaxTalkOneDay:" + MaxTalkOneDay + ","
        + "PlanHome:" + PlanHome + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}

}
