
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public partial class Tables
{
    public AIConfigCategory AIConfigCategory {get; }
    public UnitConfigCategory UnitConfigCategory {get; }
    public QUEST_Table QUESTTable {get; }
    public QUEST_DESC_Table QUESTDESCTable {get; }
    public QUEST_PLAN_Table QUESTPLANTable {get; }
    public QUEST_CONST_Table QUESTCONSTTable {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        AIConfigCategory = new AIConfigCategory(loader("aiconfigcategory"));
        UnitConfigCategory = new UnitConfigCategory(loader("unitconfigcategory"));
        QUESTTable = new QUEST_Table(loader("quest_table"));
        QUESTDESCTable = new QUEST_DESC_Table(loader("quest_desc_table"));
        QUESTPLANTable = new QUEST_PLAN_Table(loader("quest_plan_table"));
        QUESTCONSTTable = new QUEST_CONST_Table(loader("quest_const_table"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        AIConfigCategory.ResolveRef(this);
        UnitConfigCategory.ResolveRef(this);
        QUESTTable.ResolveRef(this);
        QUESTDESCTable.ResolveRef(this);
        QUESTPLANTable.ResolveRef(this);
        QUESTCONSTTable.ResolveRef(this);
    }
}

}
