
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{ 
    /// <summary>
    /// 任务完成类型
    /// </summary>
    public enum QuestType
    {
        None = 0,
        /// <summary>
        /// 英雄总等阶达到x阶
        /// </summary>
        AllHeroTotalRank = 1,
        /// <summary>
        /// 使用x个英雄战斗胜利
        /// </summary>
        BattleSuccessHeroNum = 2,
        /// <summary>
        /// 战斗获胜星级
        /// </summary>
        BattleSuccessStar = 3,
        /// <summary>
        /// 上阵x个动物升级到y级
        /// </summary>
        BattleTroopLevelNum = 4,
        /// <summary>
        /// 上阵x个y品质的动物
        /// </summary>
        BattleTroopQualityNum = 5,
        /// <summary>
        /// 上阵x个动物升级到y阶
        /// </summary>
        BattleTroopRankNum = 6,
        /// <summary>
        /// 上阵x个动物提升到y星
        /// </summary>
        BattleTroopStarNum = 7,
        /// <summary>
        /// 上阵英雄总等级达到x级
        /// </summary>
        BattleTroopTotalLevel = 8,
        /// <summary>
        /// 上阵英雄总等阶达到x阶
        /// </summary>
        BattleTroopTotalRank = 9,
        /// <summary>
        /// 上阵英雄总星级达到x星
        /// </summary>
        BattleTroopTotalStar = 10,
        /// <summary>
        /// 用x阵容完成y次战斗
        /// </summary>
        BattleWithTroop = 11,
        /// <summary>
        /// 买商店物品数量
        /// </summary>
        BuyItemNum = 12,
        /// <summary>
        /// 魅惑最后一个敌人
        /// </summary>
        CharmLastMonster = 13,
        /// <summary>
        /// 通关爬塔第x层
        /// </summary>
        ClimbingTowerNum = 14,
        /// <summary>
        /// 爬塔次数
        /// </summary>
        ClimbingTowerTimes = 15,
        /// <summary>
        /// 摧毁敌方建筑
        /// </summary>
        DestroyBuilding = 16,
        /// <summary>
        /// 抽卡次数
        /// </summary>
        DrawCardTimes = 17,
        /// <summary>
        /// 触发英雄彩蛋
        /// </summary>
        EasterEggHero = 18,
        /// <summary>
        /// 英雄死亡动画彩蛋
        /// </summary>
        EasterEggHeroAnimation = 19,
        /// <summary>
        /// 界面彩蛋
        /// </summary>
        EasterEggUI = 20,
        /// <summary>
        /// 将x个装备升级到y阶
        /// </summary>
        EquipEvolutionToRankNum = 21,
        /// <summary>
        /// 装备升级次数
        /// </summary>
        EquipUpgradeTimes = 22,
        /// <summary>
        /// 将x个装备升级到y级
        /// </summary>
        EquipUpgradeToLevelNum = 23,
        /// <summary>
        /// 用x英雄战斗一次
        /// </summary>
        FightWithHero = 24,
        /// <summary>
        /// 将x个果实升级到y阶
        /// </summary>
        FruitEvolutionToRankNum = 25,
        /// <summary>
        /// 将x个果实升级到y星
        /// </summary>
        FruitUpdateToStarNum = 26,
        /// <summary>
        /// 果实升级次数
        /// </summary>
        FruitUpgradeTimes = 27,
        /// <summary>
        /// 获得果实数量
        /// </summary>
        GetFruitNum = 28,
        /// <summary>
        /// 获得x个y品质的果实
        /// </summary>
        GetFruitQualityNum = 29,
        /// <summary>
        /// 获得英雄数量
        /// </summary>
        GetHeroNum = 30,
        /// <summary>
        /// 挂机获得x物品
        /// </summary>
        HangUpGetItem = 31,
        /// <summary>
        /// 领取挂机次数
        /// </summary>
        HangUpReceiveTimes = 32,
        /// <summary>
        /// x英雄死的次数
        /// </summary>
        HeroDieNum = 33,
        /// <summary>
        /// 单场战斗中x英雄死的次数
        /// </summary>
        HeroDieNumOneBattle = 34,
        /// <summary>
        /// 英雄升阶次数
        /// </summary>
        HeroEvolutionTimes = 35,
        /// <summary>
        /// 将x个英雄升级到y阶
        /// </summary>
        HeroEvolutionToRankNum = 36,
        /// <summary>
        /// 获得x个y品质的英雄
        /// </summary>
        HeroQualityNum = 37,
        /// <summary>
        /// 角色升级次数
        /// </summary>
        HeroUpgradeTimes = 38,
        /// <summary>
        /// 将x个英雄升级到y级
        /// </summary>
        HeroUpgradeToLevelNum = 39,
        /// <summary>
        /// 将x个英雄升级到y星
        /// </summary>
        HeroUpgradeToStarNum = 40,
        /// <summary>
        /// 单场战斗击退x个敌人
        /// </summary>
        HitBackNumOneBattle = 41,
        /// <summary>
        /// 单场战斗击飞x个敌人
        /// </summary>
        HitFlyNumOneBattle = 42,
        /// <summary>
        /// 击杀敌人数量
        /// </summary>
        KillEnemyNum = 43,
        /// <summary>
        /// 用x英雄击败y个敌人
        /// </summary>
        KillNumUseHero = 44,
        /// <summary>
        /// 单场战斗用x英雄击败y个敌人
        /// </summary>
        KillNumUseHeroOneBattle = 45,
        /// <summary>
        /// 击杀指定敌人
        /// </summary>
        KillTargetEnemy = 46,
        /// <summary>
        /// 每日登录
        /// </summary>
        LoginToday = 47,
        /// <summary>
        /// 每周登录
        /// </summary>
        LoginWeek = 48,
        /// <summary>
        /// 单场战斗单次伤害达到x
        /// </summary>
        MaxDamage = 49,
        /// <summary>
        /// 开宝箱次数
        /// </summary>
        OpenBoxTimes = 50,
        /// <summary>
        /// 开指定宝箱次数
        /// </summary>
        OpenBoxTypeTimes = 51,
        /// <summary>
        /// 通关大关
        /// </summary>
        PassBigStage = 52,
        /// <summary>
        /// 通关中关
        /// </summary>
        PassMiddleStage = 53,
        /// <summary>
        /// 通关小关
        /// </summary>
        PassSmallStage = 54,
        /// <summary>
        /// 通过关卡次数
        /// </summary>
        PassStageTimes = 55,
        /// <summary>
        /// 战力提升至x
        /// </summary>
        PowerUpdate = 56,
        /// <summary>
        /// 快速挂机次数
        /// </summary>
        QuickHangUpTimes = 57,
        /// <summary>
        /// 分享游戏次数
        /// </summary>
        ShareGameTimes = 58,
        /// <summary>
        /// 战斗技能释放次数
        /// </summary>
        SkillCastCount = 59,
        /// <summary>
        /// 单场战斗技能释放次数
        /// </summary>
        SkillCastCountOneBattle = 60,
        /// <summary>
        /// 点击技能图标次数
        /// </summary>
        SkillIconClick = 61,
        /// <summary>
        /// 点击不重复技能图标次数
        /// </summary>
        SkillIconClickNoRepeat = 62,
        /// <summary>
        /// 点击x英雄技能图标次数
        /// </summary>
        SkillIconClickOneHero = 63,
        /// <summary>
        /// 技能详情界面停留时间触发成就
        /// </summary>
        SkillView = 64,
        /// <summary>
        /// 不重复技能详情界面停留时间触发成就
        /// </summary>
        SkillViewNoRepeat = 65,
        /// <summary>
        /// x英雄技能详情界面停留时间触发成就
        /// </summary>
        SkillViewOneHero = 66,
        /// <summary>
        /// 每个模式都赢过
        /// </summary>
        SuccessAllMode = 67,
        /// <summary>
        /// 将树灵等级提升至x级
        /// </summary>
        TreeLevel = 68,
        /// <summary>
        /// 龟壳大招点击次数
        /// </summary>
        TurlteClickUltimateNum = 69,
        /// <summary>
        /// 龟壳点击释放普攻次数
        /// </summary>
        TurtleClickAttackNum = 70,
        /// <summary>
        /// 龟壳等级提升至x级
        /// </summary>
        TurtleLevel = 71,
        /// <summary>
        /// 累计水果忍者击杀怪
        /// </summary>
        LobbyKill = 72,
        /// <summary>
        /// 累计获得某物品x个（只记录时间段内获得）
        /// </summary>
        GetItemInTimePeriod = 73,
        /// <summary>
        /// 刷新商店次数
        /// </summary>
        RefreshShopTimes = 74,
        /// <summary>
        /// 累计参加主线战斗x次
        /// </summary>
        BattleTimesMainLine = 75,
        /// <summary>
        /// 限时爬塔x次
        /// </summary>
        BattleTimesLimitTimeTower = 76,
        /// <summary>
        /// 参与Pvp竞技场x次
        /// </summary>
        PvpTimes = 77,
        /// <summary>
        /// 累计投喂烧烤次数
        /// </summary>
        BBQFeedTimes = 78,
        /// <summary>
        /// 装备饰品洗练次数
        /// </summary>
        EquipJewelryUpgrade = 79,
        /// <summary>
        /// 图鉴增加x星
        /// </summary>
        HandBookStar = 80,
        /// <summary>
        /// 获得x件配饰
        /// </summary>
        GetAccessory = 81,
        /// <summary>
        /// 参与x次小游戏
        /// </summary>
        PlayMiniGames = 82,
        /// <summary>
        /// 消耗x个钻石
        /// </summary>
        DiamondCost = 83,
        /// <summary>
        /// 累计获得完整角色卡牌
        /// </summary>
        DrawCardGetHero = 84,
        /// <summary>
        /// 累计获得情报值
        /// </summary>
        CollectionPoint = 85,
        /// <summary>
        /// 完成主线任务数量
        /// </summary>
        MainLineQuestCount = 86,
        /// <summary>
        /// 累计在x类型战斗中击退y个敌人
        /// </summary>
        HitBackNumBattleType = 87,
        /// <summary>
        /// 累计在x类型战斗中击飞y个敌人
        /// </summary>
        HitFlyNumBattleType = 88,
        /// <summary>
        /// 累计水果忍者击杀奖励怪
        /// </summary>
        LobbyKillWithAward = 89,
        /// <summary>
        /// 累计在x类型战斗中魅惑y个敌人
        /// </summary>
        CharmNumBattleType = 90,
        /// <summary>
        /// 上阵六名角色装备最低达x级
        /// </summary>
        BattleTroopEquipMinLevel = 91,
        /// <summary>
        /// 上阵六名角色等级最低达x级
        /// </summary>
        BattleTroopMinLevel = 92,
        /// <summary>
        /// 累计购买红色品质物品x次
        /// </summary>
        BuyItemNumWithQuality = 93,
        /// <summary>
        /// 完成x章中所有关卡
        /// </summary>
        PassChapter = 94,
        /// <summary>
        /// 获得某一类物品的个数
        /// </summary>
        GetItemCount = 95,
        /// <summary>
        /// 明日登录
        /// </summary>
        LoginNextDay = 96,
        /// <summary>
        /// 高难度挑战关卡
        /// </summary>
        HighDifficulty = 97,
        /// <summary>
        /// 签到次数
        /// </summary>
        CheckInTimes = 98,
        /// <summary>
        /// 给N个角色穿戴装扮
        /// </summary>
        AccessoryHeroNum = 99,
        /// <summary>
        /// 给N个角色穿戴果实
        /// </summary>
        FruitHeroNum = 100,
        /// <summary>
        /// 获取指定阵营英雄n个
        /// </summary>
        CampHeroNum = 101,
        /// <summary>
        /// 今日参与过竞技场
        /// </summary>
        PvpToday = 102,
        /// <summary>
        /// 打开discord界面
        /// </summary>
        OpenDiscord = 103,
        /// <summary>
        /// 开服n日完成任务
        /// </summary>
        LoginServerDay = 104,
        /// <summary>
        /// 指定商店购买一次物品
        /// </summary>
        BuyItemWithShop = 105,
        /// <summary>
        /// 完成指定任务
        /// </summary>
        CompleteAssignedQuest = 106,
        /// <summary>
        /// 英雄共鸣等级提升至{0}级
        /// </summary>
        HeroShareLevel = 107,
        /// <summary>
        /// 无尽雨林层数
        /// </summary>
        EndlessRainforest = 108,
        /// <summary>
        /// 参与任意难度BOSS挑战{0}次
        /// </summary>
        BossBattleTimes = 109,
        /// <summary>
        /// 参与{0}难度BOSS挑战{0}次
        /// </summary>
        BossBattleLevelTimes = 110,
        /// <summary>
        /// 击败任意{0}难度BOSS挑战的首领
        /// </summary>
        BossKillLevel = 111,
        /// <summary>
        /// 当天参与竞技场{0}次
        /// </summary>
        ArenaTimesToday = 112,
        /// <summary>
        /// 累计参与竞技场{0}次
        /// </summary>
        ArenaTimes = 113,
        /// <summary>
        /// 装备共鸣等级达到{0}级
        /// </summary>
        EquipShareLevel = 114,
        /// <summary>
        /// 关注任意社群
        /// </summary>
        JoinSocialGroup = 115,
        /// <summary>
        /// 进行一次支线关卡并取得胜利
        /// </summary>
        DungeonSuccess = 116,
        /// <summary>
        /// 在广告放映厅中收看一次广告
        /// </summary>
        WatchAd = 117,
        /// <summary>
        /// 当天挑战{0}次挂机关卡
        /// </summary>
        EndlessRainforestTimesToday = 118,
        /// <summary>
        /// 当天挑战{0}次分阵营爬塔  
        /// </summary>
        LimitTowerTimesToday = 119,
        /// <summary>
        /// 完成{0}场任意战斗
        /// </summary>
        BattleSuccessWithType = 120,
        /// <summary>
        /// boss挑战玩法进入排行榜{0}次
        /// </summary>
        EnterRankTopK = 121,
        /// <summary>
        /// 使用任意数量的果实完成{0}场战斗
        /// </summary>
        BattleUseFruitNums = 122,
        /// <summary>
        /// 前往当前的主题活动
        /// </summary>
        OpenNatureActivity = 123,
        /// <summary>
        /// 累计击败{0}个大世界怪物
        /// </summary>
        KillMonsterNum = 124,
        /// <summary>
        /// 累计解锁{0}个区域的黑雾
        /// </summary>
        UnlockDungeonNum = 125,
        /// <summary>
        /// 今日boss挑战n次
        /// </summary>
        BossBattleTimesToday = 126,
        /// <summary>
        /// 转动老虎机n次
        /// </summary>
        SpinSlotMachine = 127,
        /// <summary>
        /// 转到n个相同的图章m次
        /// </summary>
        SpinSameSealTimes = 128,
        /// <summary>
        /// 老虎机击杀野蛮人n次
        /// </summary>
        SlotMachineKillEnemyTimes = 129,
        /// <summary>
        /// 消耗n个m道具
        /// </summary>
        ItemCost = 130,
        /// <summary>
        /// 老虎机玩法获取n积分
        /// </summary>
        GetSlotMachineScore = 131,
        /// <summary>
        /// Boss全服首次击杀
        /// </summary>
        BossFirstKill = 132,
        /// <summary>
        /// 在指定topshop中购买一次物品
        /// </summary>
        BuyItemWithTopShop = 133,
        /// <summary>
        /// 首次付费n元
        /// </summary>
        CumulativePay = 134,
        /// <summary>
        /// 抵达vip等级n
        /// </summary>
        GiftAfterVIP = 135,
        /// <summary>
        /// 在公屏连续发言10天
        /// </summary>
        SpeakInPublicChatDays = 136,
        /// <summary>
        /// 单次十连出了两张及以上红卡整卡
        /// </summary>
        CardsInTenDraw = 137,
        /// <summary>
        /// 连续三次十连没出整卡
        /// </summary>
        NoAdvancedCardsInDraw = 138,
        /// <summary>
        /// 累计使用100个果实
        /// </summary>
        UseFruitsCount = 139,
        /// <summary>
        /// 连续胜利次数30次
        /// </summary>
        ConsecutiveVictories = 140,
        /// <summary>
        /// 连续失败次数30次
        /// </summary>
        ConsecutiveDefeats = 141,
        /// <summary>
        /// 在xxx小游戏中获得xxx积分
        /// </summary>
        EarnPointsInMiniGame = 142,
        /// <summary>
        /// 借给其他人英雄数量达到n个
        /// </summary>
        FriendBorrowHeroCount = 143,
        /// <summary>
        /// 好友数量达成n个
        /// </summary>
        FriendCount = 144,
        /// <summary>
        /// 将x个英雄升级y级
        /// </summary>
        HeroLevelUpgrade = 145,
        /// <summary>
        /// 将x个英雄升级y星
        /// </summary>
        HeroStarUpgrade = 146,
        /// <summary>
        /// 参与n次任意休闲游戏
        /// </summary>
        PlayCasualGame = 147,
        /// <summary>
        /// 参与{0}次2048小游戏
        /// </summary>
        JoinCountIn2048 = 148,
        /// <summary>
        /// 在2048小游戏中获胜{0}次
        /// </summary>
        WinCountIn2048 = 149,
        /// <summary>
        /// 2048小游戏达到{0}段位
        /// </summary>
        GradeLeveIn2048 = 150,
        /// <summary>
        /// 排名赛挑战N次
        /// </summary>
        ArenaRankChallengeCount = 151,
        /// <summary>
        /// 排名赛使用X名奖励英雄挑战N次
        /// </summary>
        ArenaRankUsePickChallengeCount = 152,
        /// <summary>
        /// 排名赛使用X名奖励英雄胜利N次
        /// </summary>
        ArenaRankUsePickWinCount = 153,
        /// <summary>
        /// 排名赛提升排名
        /// </summary>
        ArenaRankRankingUp = 154,
        /// <summary>
        /// 排名赛最高排名
        /// </summary>
        ArenaRankRankingTop = 155,
        /// <summary>
        /// 累计签到次数
        /// </summary>
        CheckInAccumulated = 156,
        /// <summary>
        /// 排名赛有效挑战次数
        /// </summary>
        ArenaRankEffectiveChallengeCount = 157,
        /// <summary>
        /// 排名赛挑战胜利次数
        /// </summary>
        ArenaRankChallengeWinCount = 158,
        /// <summary>
        /// 在动物擂台中通关指定次数
        /// </summary>
        ClearStagesInAnimalArenaTimes = 159,
        /// <summary>
        /// 在动物擂台中扫荡指定次数
        /// </summary>
        SweepStagesInAnimalArenaTimes = 160,
        /// <summary>
        /// 通关动物擂台的指定回合次数
        /// </summary>
        ClearAnimalArenaRoundTimes = 161,
        /// <summary>
        /// 连续参加动物擂台的天数
        /// </summary>
        ConsecutiveDaysInAnimalArena = 162,
        /// <summary>
        /// 在动物擂台中获得的星星数
        /// </summary>
        EarnStarsInAnimalArena = 163,
        /// <summary>
        /// 动物擂台通关第n关
        /// </summary>
        PassAnimalArenaLevel = 164,
        /// <summary>
        /// 发送n次好友申请
        /// </summary>
        SendFriendRequests = 165,
        /// <summary>
        /// 通关指定困难关卡
        /// </summary>
        ClearSpecifiedHardLevel = 166,
        /// <summary>
        /// 段位竞技场达到n积分
        /// </summary>
        ReachRankedArenaPoints = 167,
        /// <summary>
        /// 埃及活动通关简单关卡
        /// </summary>
        EgyptStageNormal = 168,
        /// <summary>
        /// 埃及活动通关困难关卡
        /// </summary>
        EgyptStageDifficult = 169,
        /// <summary>
        /// 埃及活动通关次数
        /// </summary>
        EgyptStageTimes = 170,
        /// <summary>
        /// 阵容收集获得英雄数量
        /// </summary>
        TeamRecommendCollection = 171,
        /// <summary>
        /// 阵容收集查看演示视频
        /// </summary>
        TeamRecommendWatchVideo = 172,
        /// <summary>
        /// 在家园开启{0}次清扫工作
        /// </summary>
        StartCleaningInHomeXTimes = 173,
        /// <summary>
        /// 在家园完成{0}次清扫工作
        /// </summary>
        CompleteCleaningInHomeXTimes = 174,
        /// <summary>
        /// 在家园商城购买指定物品{0}次
        /// </summary>
        PurchaseItemInHomeStoreXTimes = 175,
        /// <summary>
        /// 在家园中投喂老爷爷巧克力{0}次
        /// </summary>
        FeedGrandpaChocolateXTimes = 176,
        /// <summary>
        /// 在家园中累计拾取金币{0}枚
        /// </summary>
        CollectCoinsInHomeXTimes = 177,
        /// <summary>
        /// 在家园中放置{0}枚家园蛋
        /// </summary>
        PlaceHomeEggsXTimes = 178,
        /// <summary>
        /// 在家园中完成{0}次孵化
        /// </summary>
        CompleteHatchingInHomeXTimes = 179,
        /// <summary>
        /// 在家园中触发{0}次蛋的变异
        /// </summary>
        TriggerEggMutationInHomeXTimes = 180,
        /// <summary>
        /// 完成指定品质英雄的孵化{0}次
        /// </summary>
        HatchHeroesOfQualityXTimes = 181,
        /// <summary>
        /// 在家园中满足英雄的任意/指定需求{0}次
        /// </summary>
        SatisfyHeroNeedsInHomeXTimes = 182,
        /// <summary>
        /// 家园树等级提升至{0}级
        /// </summary>
        UpgradeHomeTreeToLevelX = 183,
        /// <summary>
        /// 主线累计通关{0}关
        /// </summary>
        ClearStagesMainline = 184,
        /// <summary>
        /// 主线收集{0}个星星
        /// </summary>
        CollectStarsMainline = 185,
        /// <summary>
        /// 主线通关{0}关在获取任务后
        /// </summary>
        ClearStagesMainlineAcquired = 186,
        /// <summary>
        /// 主线收集{0}个星星在获取任务后
        /// </summary>
        CollectStarsMainlineAcquired = 187,
        /// <summary>
        /// 在英雄试炼中获胜{0}次
        /// </summary>
        WinCountInHeroTrial = 188,
        /// <summary>
        /// 在英雄试炼中获得{0}颗星
        /// </summary>
        GetStarCountInHeroTrial = 189,
        /// <summary>
        /// 地心探索获胜{0}次
        /// </summary>
        WinCountInExploreGeoCenter = 190,
        /// <summary>
        /// 完成{0}次老虎机或2048
        /// </summary>
        BattleCountInSlotMachineOr2048 = 191,
        /// <summary>
        /// x个角色的宝石套装到y级
        /// </summary>
        HeroGemSuitLevelCount = 192,
        /// <summary>
        /// 拥有x个y级宝石
        /// </summary>
        HeroGemUpgradeToLevel = 193,
        /// <summary>
        /// 帮派捐献n次
        /// </summary>
        GuildDonationNTimes = 194,
        /// <summary>
        /// 完成n个好友订单
        /// </summary>
        CompleteNFriendOrders = 195,
        /// <summary>
        /// 冠军竞技场胜利N次
        /// </summary>
        ArenaChampionTimes = 196,
        /// <summary>
        /// 冠军竞技场排名达到N以内
        /// </summary>
        ArenaChampionRank = 197,
        /// <summary>
        /// 挑战主线普通关卡N次
        /// </summary>
        MainlineNormalTimes = 198,
        /// <summary>
        /// 挑战困难主线关卡N次
        /// </summary>
        MainlineDifficultTimes = 199,
        /// <summary>
        /// 参与英雄试炼N次
        /// </summary>
        HeroTrialNTimes = 200,
        /// <summary>
        /// 参与地心探索N次
        /// </summary>
        GeocentricExplorationNTimes = 201,
        /// <summary>
        /// 参与N次段位竞技场
        /// </summary>
        ArenaSegmentNTimes = 202,
        /// <summary>
        /// 加入帮派
        /// </summary>
        JoinGuild = 203,
        /// <summary>
        /// 镶嵌{0}颗宝石
        /// </summary>
        PageInlayNTimes = 204,
        /// <summary>
        /// 在装扮商城中购买{0}次商品
        /// </summary>
        AccShopBuyNTimes = 205,
        /// <summary>
        /// 参与N次寻宝探险
        /// </summary>
        TreasureCaveNTimes = 206,
        /// <summary>
        /// 完成任意N条帮派任务
        /// </summary>
        CompleteGuildTaskNTimes = 207,
        /// <summary>
        /// 参与动物擂台有结算一次
        /// </summary>
        AnimalBattleJoinOnce = 208,
        /// <summary>
        /// 完成周活的所有任务
        /// </summary>
        CompleteAllWeeklyQuests = 209,
        /// <summary>
        /// 帮派完成第n阶段击杀
        /// </summary>
        GuildBossStageNKill = 210,
        /// <summary>
        /// 参与n次帮派Boss挑战
        /// </summary>
        ChallengeGuildBossNTimes = 211,
        /// <summary>
        /// 累计对帮派Boss造成n点伤害
        /// </summary>
        GuildBossDealNDamage = 212,
        /// <summary>
        /// 消耗体力{0}点
        /// </summary>
        ConsumeStamina = 213,
        /// <summary>
        /// 购买体力{0}次
        /// </summary>
        BuyStamina = 214,
        /// <summary>
        /// 使用{0}次好感度道具
        /// </summary>
        UseFriendshipItem = 215,
        /// <summary>
        /// 领取{0}次家园体力
        /// </summary>
        ClaimHomeStamina = 216,
        /// <summary>
        /// 完成{0}次家园任务
        /// </summary>
        HomeTaskComplete = 217,
        /// <summary>
        /// 果实抽卡{0}次
        /// </summary>
        FruitGacha = 218,
        /// <summary>
        /// 领取{0}次竞技场挂机奖励
        /// </summary>
        ClaimArenaIdleReward = 219,
        /// <summary>
        /// 装扮商城购买{0}次
        /// </summary>
        CosmeticShopPurchase = 220,
        /// <summary>
        /// 累计充值{0}
        /// </summary>
        TotalRecharge = 221,
        /// <summary>
        /// 普通主线通过{0}
        /// </summary>
        NormalMainlinePass = 222,
        /// <summary>
        /// 家园树高度到达{0}
        /// </summary>
        HomeTreeHeight = 223,
        /// <summary>
        /// 家园商店购买{0}次
        /// </summary>
        HomeShopPurchase = 224,
        /// <summary>
        /// 添加{0}名好友
        /// </summary>
        AddFriend = 225,
        /// <summary>
        /// 帮派商店购买{0}次
        /// </summary>
        GuildShopPurchase = 226,
        /// <summary>
        /// 困难关卡通过{0}
        /// </summary>
        HardLevelPass = 227,
        /// <summary>
        /// 挑战{0}次帮派boss
        /// </summary>
        GuildBossChallenge = 228,
        /// <summary>
        /// 通关/扫荡{0}次体力副本
        /// </summary>
        StaminaDungeonPassSweep = 229,
        /// <summary>
        /// 今日通关/扫荡{0}次体力副本
        /// </summary>
        StaminaDungeonPassSweepInToday = 230,
        /// <summary>
        /// 动物擂台通过{0}关
        /// </summary>
        AnimalArenaPass = 231,
        /// <summary>
        /// 动物擂台扫荡{0}次
        /// </summary>
        AnimalArenaSweep = 232,
        /// <summary>
        /// 参与{0}次寻宝探险
        /// </summary>
        ParticipateTreasureHunt = 233,
        /// <summary>
        /// 完成{0}次寻宝探险
        /// </summary>
        CompleteTreasureHunt = 234,
        /// <summary>
        /// 每日Boss挑战{0}次
        /// </summary>
        DailyBossChallenge = 235,
        /// <summary>
        /// 每日Boss {0}难度达到{1}%
        /// </summary>
        DailyBossDifficultyPercentage = 236,
        /// <summary>
        /// 击败{0}次{1}难度Boss
        /// </summary>
        DefeatBossAtDifficulty = 237,
        /// <summary>
        /// 挑战{0}名玩家
        /// </summary>
        ChallengePlayer = 238,
        /// <summary>
        /// 拥有{0}名追随者
        /// </summary>
        HaveFollower = 239,
        /// <summary>
        /// 收取{0}次上贡资源
        /// </summary>
        CollectTributeResource = 240,
        /// <summary>
        /// 赠送{0}次追随奖励
        /// </summary>
        GiveFollowReward = 241,
        /// <summary>
        /// 参与{0}次阵营爬塔
        /// </summary>
        CampTowerParticipation = 242,
        /// <summary>
        /// 阵营爬塔胜利{0}次
        /// </summary>
        CampTowerVictory = 243,
        /// <summary>
        /// 任意阵营爬塔达到{0}关
        /// </summary>
        CampTowerReachLevel = 244,
        /// <summary>
        /// 挑战{0}次英雄试炼
        /// </summary>
        HeroTrialChallenge = 245,
        /// <summary>
        /// 英雄试炼成功挑战{0}次
        /// </summary>
        HeroTrialSuccessChallenge = 246,
        /// <summary>
        /// 英雄试炼扫荡{0}次
        /// </summary>
        HeroTrialSweep = 247,
        /// <summary>
        /// 挑战{0}次地心试炼
        /// </summary>
        CoreTrialChallenge = 248,
        /// <summary>
        /// 地心探索通关{0}次
        /// </summary>
        CoreExplorationPass = 249,
        /// <summary>
        /// 地心试炼扫荡{0}次
        /// </summary>
        CoreTrialSweep = 250,
        /// <summary>
        /// 野人入侵通过{0}关
        /// </summary>
        SavageInvasionPass = 251,
        /// <summary>
        /// 装备精炼{0}次
        /// </summary>
        EquipmentRefinement = 252,
        /// <summary>
        /// 提升{0}次精灵图鉴
        /// </summary>
        SpiritPokedexUpgrade = 253,
        /// <summary>
        /// 头衔达到{0}
        /// </summary>
        TitleReach = 254,
        /// <summary>
        /// 战力达到{0}
        /// </summary>
        CombatPowerReach = 255,
        /// <summary>
        /// 主角达到{0}级
        /// </summary>
        PlayerLevelReach = 256,
        /// <summary>
        /// 上阵{0}名英雄
        /// </summary>
        HeroOnField = 257,
        /// <summary>
        /// 上阵{0}名{1}品质英雄
        /// </summary>
        HeroOfQualityOnField = 258,
        /// <summary>
        /// 英雄共鸣等级达到{0}
        /// </summary>
        HeroResonanceLevel = 259,
        /// <summary>
        /// {0}名英雄达到{1}阶
        /// </summary>
        HeroReachStage = 260,
        /// <summary>
        /// {0}个角色装备达到{1}级
        /// </summary>
        CharacterEquipmentLevel = 261,
        /// <summary>
        /// {0}个角色装备精炼至{1}级
        /// </summary>
        CharacterEquipmentRefinedLevel = 262,
        /// <summary>
        /// 合成{0}次任意类型宝石
        /// </summary>
        SynthesizeAnyTypeGemstoneNTimes = 263,
        /// <summary>
        /// 装备洗练{0}次
        /// </summary>
        EquipmentScrub = 264,
        /// <summary>
        /// {0}阵营技提升至{1}阶{2}级
        /// </summary>
        CampSkillUpgrade = 265,
        /// <summary>
        /// {0}阵营技进化至{1}色{2}星
        /// </summary>
        CampSkillEvolve = 266,
        /// <summary>
        /// {0}个阵营技能提升至{1}阶{2}级
        /// </summary>
        CampSkillLevelUp = 267,
        /// <summary>
        /// 精灵图鉴提升至{0}级
        /// </summary>
        SpiritPokedexLevel = 268,
        /// <summary>
        /// 镶嵌{0}个{1}级{2}类型宝石
        /// </summary>
        WearUnspecifiedLevelAndTypeGem = 269,
        /// <summary>
        /// {0}个角色好感度达到{1}级
        /// </summary>
        CharacterFriendshipLevel = 270,
        /// <summary>
        /// 羁绊总等级达到{0}级
        /// </summary>
        BondTotalLevel = 271,
        /// <summary>
        /// 单个羁绊达到{0}级
        /// </summary>
        BondLevel = 272,
        /// <summary>
        /// {0}角色好感度达到{1}级
        /// </summary>
        CharacterFriendshipReach = 273,
        /// <summary>
        /// 将{0}个{1}品质英雄升至{2}星
        /// </summary>
        HeroUpgradeToStar = 274,
        /// <summary>
        /// 将{0}个英雄觉醒至{1}级
        /// </summary>
        HeroAwakenLevel = 275,
        /// <summary>
        /// 将{0}件装备打造至{1}品质
        /// </summary>
        CraftEquipmentsToYQuality = 276,
        /// <summary>
        /// {0}件装备精炼至+{1}
        /// </summary>
        EquipmentRefinedLevel = 277,
        /// <summary>
        /// 将{0}个果实升至{1}阶
        /// </summary>
        FruitUpgradeToStage = 278,
        /// <summary>
        /// 将{0}个果实升至{1}星
        /// </summary>
        FruitUpgradeToStar = 279,
        /// <summary>
        /// {0}个角色镶嵌{1}宝石
        /// </summary>
        CharacterInlayGem = 280,
        /// <summary>
        /// {0}个{1}宝石升至{3}级
        /// </summary>
        GemUpgradeToLevel = 281,
        /// <summary>
        /// 达到寻宝探险第{0}层{1}次
        /// </summary>
        TreasureCaveLevel = 282,
        /// <summary>
        /// 在冒险中触发{0}色光芒{1}次
        /// </summary>
        AdventureRays = 283,
        /// <summary>
        /// 在冒险中累计撞飞{0}只怪物
        /// </summary>
        AdventureHitMonster = 284,
        /// <summary>
        /// 在不使用{0}职业的前提下，完成关卡{1}
        /// </summary>
        NoJobFinishStage = 285,
        /// <summary>
        /// 在不使用{0}阵营的前提下，造成{1}伤害
        /// </summary>
        NoCampFinishStage = 286,
        /// <summary>
        /// 一场战斗中释放{0}次阵营技
        /// </summary>
        CampSkillMaxNum = 287,
        /// <summary>
        /// 一场战斗中释放{0}次子弹技能
        /// </summary>
        TurpleSkillMaxNum = 288,
        /// <summary>
        /// 完成第{0}章中所有关卡
        /// </summary>
        ChapterFinish = 289,
        /// <summary>
        /// 在家园树领取{0}次神树种子
        /// </summary>
        ClaimHomeTreeSeed = 290,
        /// <summary>
        /// 拥有x个阵营技
        /// </summary>
        CampSkillCount = 291,
        /// <summary>
        /// 升级x次阵营技
        /// </summary>
        CampSkillUpgradeTimes = 292,
        /// <summary>
        /// x个阵营技提升到y星
        /// </summary>
        CampSkillUpToStarLevel = 293,
        /// <summary>
        /// 提升x次阵营技星级
        /// </summary>
        CampSkillUpStarTimes = 294,
        /// <summary>
        /// 挑战{0}次世界Boss
        /// </summary>
        ChallengeWorldBossNTimes = 295,
        /// <summary>
        /// 普通狩猎场累计造成{0}伤害
        /// </summary>
        NormalHuntingCumulativeDamage = 296,
        /// <summary>
        /// 高级狩猎场累计造成{0}伤害
        /// </summary>
        AdvancedHuntingCumulativeDamage = 297,
        /// <summary>
        /// 在世界Boss挑战中获得{0}次第一名
        /// </summary>
        WorldBossNTimesFirst = 298,
        /// <summary>
        /// 好感度总等级到{0}级
        /// </summary>
        FettersLevelReach = 299,
        /// <summary>
        /// 挑战副本评分达到{0}分
        /// </summary>
        ChallengeDungeonScore = 300,
        /// <summary>
        /// 限时活动主线副本中通关{0}次
        /// </summary>
        ClearMainStoryDungeonTimes = 301,
        /// <summary>
        /// 限时活动主线副本中通关第{0}关
        /// </summary>
        ClearMainStoryDungeonLevel = 302,
        /// <summary>
        /// 活动期间登录{0}次
        /// </summary>
        LoginTimesDuringEvent = 303,
        /// <summary>
        /// 累计充值额度达到{0}
        /// </summary>
        CumulativeRechargeAmountReached = 304,
        /// <summary>
        /// 累计充值{0}次
        /// </summary>
        CumulativeRechargeTimes = 305,
        /// <summary>
        /// {指定周期内}充值{1}次
        /// </summary>
        RechargeTimesInSpecifiedPeriod = 306,
        /// <summary>
        /// {指定周期内}充值额度达到{1}
        /// </summary>
        RechargeAmountReachedInSpecifiedPeriod = 307,
        /// <summary>
        /// 连续充值{0}天
        /// </summary>
        ConsecutiveRechargeDays = 308,
        /// <summary>
        /// 累计拥有月卡{0}天
        /// </summary>
        CumulativeMonthlyCardDays = 309,
        /// <summary>
        /// 声望值到达{0}
        /// </summary>
        ReputationReaches = 310,
        /// <summary>
        /// {0}个追随者忠诚度大于等于{1}
        /// </summary>
        FollowersLoyaltyGreaterThanOrEqualTo = 311,
        /// <summary>
        /// {0}个追随者忠诚度小于等于{1}
        /// </summary>
        FollowersLoyaltyLessThanOrEqualTo = 312,
        /// <summary>
        /// {0}个追随者忠诚度等于{1}
        /// </summary>
        FollowersLoyaltyEqualTo = 313,
        /// <summary>
        /// 完成{0}次玩家PK战斗
        /// </summary>
        PlayerPKBattleTimes = 314,
        /// <summary>
        /// 打造{0}个{1}部件
        /// </summary>
        CreateEquipComponents = 315,
        /// <summary>
        /// 游玩墙壁弹球游戏{0}次
        /// </summary>
        GameTheWallPlayTimes = 316,
        /// <summary>
        /// 墙壁弹球游戏累计积分达到{0}
        /// </summary>
        GameTheWallTotalScore = 317,
    }

} 

