
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
[Config]
public partial class QUEST_CONST_Table: Singleton<QUEST_CONST_Table>
{

     private readonly QUEST_CONST _data;

    public QUEST_CONST_Table(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::ET.QUEST_CONST.DeserializeQUEST_CONST(_buf);
    }


    /// <summary>
    /// 日常任务方案
    /// </summary>
     public int PlanDaily => _data.PlanDaily;
    /// <summary>
    /// 周常任务方案
    /// </summary>
     public int PlanWeekly => _data.PlanWeekly;
    /// <summary>
    /// 日常周常任务最大刷新数量
    /// </summary>
     public int MaxQuestCount => _data.MaxQuestCount;
    /// <summary>
    /// 每天发言最多的人邮件
    /// </summary>
     public int MaxTalkOneDay => _data.MaxTalkOneDay;
    /// <summary>
    /// 家园任务方案
    /// </summary>
     public int PlanHome => _data.PlanHome;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
        PostResolve();
    }
    partial void PostInit();
    partial void PostResolve();
}

}
