
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{ 
    /// <summary>
    /// 任务类型
    /// </summary>
    public enum QuestCategory
    {
        None = 0,
        /// <summary>
        /// 主线任务
        /// </summary>
        Mainline = 1,
        /// <summary>
        /// 每日任务
        /// </summary>
        Daily = 2,
        /// <summary>
        /// 每周任务
        /// </summary>
        Weekly = 3,
        /// <summary>
        /// 树灵任务
        /// </summary>
        Tree = 4,
        /// <summary>
        /// 不会刷新的任务
        /// </summary>
        Achievement = 5,
        /// <summary>
        /// 阵容收集任务
        /// </summary>
        Collection = 6,
        /// <summary>
        /// 游戏2048每日刷新任务
        /// </summary>
        Game2048Daily = 7,
        /// <summary>
        /// 游戏2048周期刷新任务
        /// </summary>
        Game2048 = 8,
        /// <summary>
        /// 游戏老虎机每日刷新任务
        /// </summary>
        GameSlotMachineDaily = 9,
        /// <summary>
        /// 游戏老虎机周期刷新任务
        /// </summary>
        GameSlotMachine = 10,
        /// <summary>
        /// 埃及活动
        /// </summary>
        Egypt = 11,
        /// <summary>
        /// 埃及活动关卡
        /// </summary>
        EgyptChapter = 12,
        /// <summary>
        /// 头像框
        /// </summary>
        AvatarFrame = 13,
        /// <summary>
        /// 排名赛每周任务
        /// </summary>
        ArenaRankWeekly = 14,
        /// <summary>
        /// 家园任务
        /// </summary>
        Home = 15,
        /// <summary>
        /// 周常活动
        /// </summary>
        WeeklyActivity = 16,
        /// <summary>
        /// 埃及活动任务
        /// </summary>
        EgyptActivity = 17,
        /// <summary>
        /// 英雄试炼
        /// </summary>
        HeroTrial = 18,
        /// <summary>
        /// .地心探索
        /// </summary>
        ExploreGeoCenter = 19,
        /// <summary>
        /// 公会每日任务
        /// </summary>
        GuildDaily = 20,
        /// <summary>
        /// 公会挑战任务
        /// </summary>
        GuildChallenge = 21,
        /// <summary>
        /// 帮派Boss任务
        /// </summary>
        GuildBoss = 22,
        /// <summary>
        /// 新人目标任务
        /// </summary>
        NoviceTarget = 23,
        /// <summary>
        /// 果实狂热任务
        /// </summary>
        FruitFrenzy = 24,
        /// <summary>
        /// 英雄养成目标
        /// </summary>
        HeroCultivateTarget = 25,
        /// <summary>
        /// 果实养成目标
        /// </summary>
        FruitCultivateTarget = 26,
        /// <summary>
        /// 装备养成目标
        /// </summary>
        HeroEquipCultivateTarget = 27,
        /// <summary>
        /// 宝石养成目标
        /// </summary>
        GemCultivateTarget = 28,
        /// <summary>
        /// 追随者系统相关任务
        /// </summary>
        FollowerSys = 29,
        /// <summary>
        /// 丛林声望
        /// </summary>
        JunglePrestige = 30,
        /// <summary>
        /// 追随者系统副任务面板
        /// </summary>
        FollowerSysSub = 31,
        /// <summary>
        /// 墙壁弹球小游戏周期刷新任务
        /// </summary>
        GameTheWall = 32,
        /// <summary>
        /// 角色限定活动任务
        /// </summary>
        HeroThemeEvent = 33,
    }

} 

