
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
[Config]
public partial class QUEST_DESC_Table: Singleton<QUEST_DESC_Table>
{
    private readonly System.Collections.Generic.Dictionary<QuestType, QUEST_DESC> _dataMap;
    private readonly System.Collections.Generic.List<QUEST_DESC> _dataList;
    
    public QUEST_DESC_Table(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<QuestType, QUEST_DESC>();
        _dataList = new System.Collections.Generic.List<QUEST_DESC>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            QUEST_DESC _v;
            _v = global::ET.QUEST_DESC.DeserializeQUEST_DESC(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.QuestType, _v);
        }
        PostInit();
    }

    public System.Collections.Generic.Dictionary<QuestType, QUEST_DESC> DataMap => _dataMap;
    public System.Collections.Generic.List<QUEST_DESC> DataList => _dataList;

    public QUEST_DESC GetOrDefault(QuestType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public QUEST_DESC Get(QuestType key) => _dataMap[key];
    public QUEST_DESC this[QuestType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        PostResolve();
    }

    partial void PostInit();
    partial void PostResolve();
}

}
