
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public sealed partial class QUEST_DESC : Luban.BeanBase
{
    public QUEST_DESC(ByteBuf _buf) 
    {
        QuestType = (QuestType)_buf.ReadInt();
        Description = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Descriptions = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Descriptions.Add(_e0);}}
        JumpLinkId = _buf.ReadInt();
        Tips = _buf.ReadInt();
        PostInit();
    }

    public static QUEST_DESC DeserializeQUEST_DESC(ByteBuf _buf)
    {
        return new QUEST_DESC(_buf);
    }

    /// <summary>
    /// 任务类型，有什么类型具体看enum.xlsx
    /// </summary>
    public readonly QuestType QuestType;
    /// <summary>
    /// 任务描述[Text]
    /// </summary>
    public readonly int Description;
    /// <summary>
    /// 任务描述,需要根据参数判断[Text]
    /// </summary>
    public readonly System.Collections.Generic.List<int> Descriptions;
    /// <summary>
    /// 跳链id
    /// </summary>
    public readonly int JumpLinkId;
    /// <summary>
    /// 如果不是跳链，显示该tips[Text]
    /// </summary>
    public readonly int Tips;
   
    public const int __ID__ = 1090369518;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "QuestType:" + QuestType + ","
        + "Description:" + Description + ","
        + "Descriptions:" + Luban.StringUtil.CollectionToString(Descriptions) + ","
        + "JumpLinkId:" + JumpLinkId + ","
        + "Tips:" + Tips + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}

}
