
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public sealed partial class QUEST_PLAN : Luban.BeanBase
{
    public QUEST_PLAN(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Category = (QuestCategory)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);QuestIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); QuestIds.Add(_e0);}}
        PostInit();
    }

    public static QUEST_PLAN DeserializeQUEST_PLAN(ByteBuf _buf)
    {
        return new QUEST_PLAN(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 任务类别
    /// </summary>
    public readonly QuestCategory Category;
    /// <summary>
    /// 任务id
    /// </summary>
    public readonly System.Collections.Generic.List<int> QuestIds;
   
    public const int __ID__ = 1090733190;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Category:" + Category + ","
        + "QuestIds:" + Luban.StringUtil.CollectionToString(QuestIds) + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}

}
