
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
[Config]
public partial class QUEST_Table: Singleton<QUEST_Table>
{
    private readonly System.Collections.Generic.Dictionary<int, QUEST> _dataMap;
    private readonly System.Collections.Generic.List<QUEST> _dataList;
    
    public QUEST_Table(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, QUEST>();
        _dataList = new System.Collections.Generic.List<QUEST>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            QUEST _v;
            _v = global::ET.QUEST.DeserializeQUEST(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, QUEST> DataMap => _dataMap;
    public System.Collections.Generic.List<QUEST> DataList => _dataList;

    public QUEST GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public QUEST Get(int key) => _dataMap[key];
    public QUEST this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        PostResolve();
    }

    partial void PostInit();
    partial void PostResolve();
}

}
