
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
[Config]
public partial class StartMachineConfigCategory: Singleton<StartMachineConfigCategory>
{
    private readonly System.Collections.Generic.Dictionary<int, StartMachineConfig> _dataMap;
    private readonly System.Collections.Generic.List<StartMachineConfig> _dataList;
    
    public StartMachineConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, StartMachineConfig>();
        _dataList = new System.Collections.Generic.List<StartMachineConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            StartMachineConfig _v;
            _v = global::ET.StartMachineConfig.DeserializeStartMachineConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, StartMachineConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<StartMachineConfig> DataList => _dataList;

    public StartMachineConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StartMachineConfig Get(int key) => _dataMap[key];
    public StartMachineConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        PostResolve();
    }

    partial void PostInit();
    partial void PostResolve();
}

}
