
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
[Config]
public partial class StartSceneConfigCategory: Singleton<StartSceneConfigCategory>
{
    private readonly System.Collections.Generic.Dictionary<int, StartSceneConfig> _dataMap;
    private readonly System.Collections.Generic.List<StartSceneConfig> _dataList;
    
    public StartSceneConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, StartSceneConfig>();
        _dataList = new System.Collections.Generic.List<StartSceneConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            StartSceneConfig _v;
            _v = global::ET.StartSceneConfig.DeserializeStartSceneConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, StartSceneConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<StartSceneConfig> DataList => _dataList;

    public StartSceneConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StartSceneConfig Get(int key) => _dataMap[key];
    public StartSceneConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        PostResolve();
    }

    partial void PostInit();
    partial void PostResolve();
}

}
