
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public partial class Tables
{
    public StartMachineConfigCategory StartMachineConfigCategory {get; }
    public StartProcessConfigCategory StartProcessConfigCategory {get; }
    public StartSceneConfigCategory StartSceneConfigCategory {get; }
    public StartZoneConfigCategory StartZoneConfigCategory {get; }
    public AIConfigCategory AIConfigCategory {get; }
    public UnitConfigCategory UnitConfigCategory {get; }
    public QUEST_Table QUESTTable {get; }
    public QUEST_PLAN_Table QUESTPLANTable {get; }
    public QUEST_CONST_Table QUESTCONSTTable {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        StartMachineConfigCategory = new StartMachineConfigCategory(loader("startmachineconfigcategory"));
        StartProcessConfigCategory = new StartProcessConfigCategory(loader("startprocessconfigcategory"));
        StartSceneConfigCategory = new StartSceneConfigCategory(loader("startsceneconfigcategory"));
        StartZoneConfigCategory = new StartZoneConfigCategory(loader("startzoneconfigcategory"));
        AIConfigCategory = new AIConfigCategory(loader("aiconfigcategory"));
        UnitConfigCategory = new UnitConfigCategory(loader("unitconfigcategory"));
        QUESTTable = new QUEST_Table(loader("quest_table"));
        QUESTPLANTable = new QUEST_PLAN_Table(loader("quest_plan_table"));
        QUESTCONSTTable = new QUEST_CONST_Table(loader("quest_const_table"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        StartMachineConfigCategory.ResolveRef(this);
        StartProcessConfigCategory.ResolveRef(this);
        StartSceneConfigCategory.ResolveRef(this);
        StartZoneConfigCategory.ResolveRef(this);
        AIConfigCategory.ResolveRef(this);
        UnitConfigCategory.ResolveRef(this);
        QUESTTable.ResolveRef(this);
        QUESTPLANTable.ResolveRef(this);
        QUESTCONSTTable.ResolveRef(this);
    }
}

}
