
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET.test2
{
/// <summary>
/// 矩形
/// </summary>
public sealed partial class Rectangle : test.Shape
{
    public Rectangle(ByteBuf _buf)  : base(_buf) 
    {
        Width = _buf.ReadFloat();
        PostInit();
    }

    public static Rectangle DeserializeRectangle(ByteBuf _buf)
    {
        return new test2.Rectangle(_buf);
    }

    /// <summary>
    /// 宽度
    /// </summary>
    public readonly float Width;
   
    public const int __ID__ = 694982337;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "width:" + Width + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}

}
